#
# syntax: https://docs.docker.com/compose/yml/
# author: cuongnb14@gmail.com
#

version: "3"

services:

  logstash:
      image: cuongnb14/logstash
      networks:
          - back-tier
      volumes:
          - ./logstash-config/:/conf/
          - ./logs/:/logs/
      command: logstash -f /conf/agent.conf
      hostname: logstash-agent
      domainname: container.box
      stdin_open: true
      logging:
          driver: "json-file"
          options:
              max-size: "100M"
              max-file: "3"

  influxdb:
    image: influxdb:alpine 
    environment:
      - INFLUXDB_DB=metrics
    networks:
      - back-tier

networks:
    back-tier: